{{- if and .Values.backend.enabled .Values.backend.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "eks-setup-app.backend.serviceAccountName" . }}
  labels:
    {{- include "eks-setup-app.labels" . | nindent 4 }}
    {{- include "eks-setup-app.componentLabels" (dict "component" "backend" "Release" .Release "Chart" .Chart "Values" .Values) | nindent 4 }}
  {{- with .Values.backend.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}


