{{- if .Values.externalSecrets.enabled -}}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Values.externalSecrets.secretStore.name }}
  labels:
    {{- include "eks-setup-app.labels" . | nindent 4 }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.externalSecrets.secretStore.region | quote }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecrets.backend.externalSecretName }}
  labels:
    {{- include "eks-setup-app.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.backend.refreshInterval | quote }}
  secretStoreRef:
    kind: SecretStore
    name: {{ .Values.externalSecrets.secretStore.name }}
  target:
    name: {{ .Values.externalSecrets.backend.targetSecretName }}
    creationPolicy: Owner
  data:
    {{- range .Values.externalSecrets.backend.data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ $.Values.externalSecrets.backend.awsSecretName | quote }}
        property: {{ .remoteKey | quote }}
    {{- end }}
{{- end }}


