{{- if and .Values.frontend.enabled .Values.frontend.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default (printf "%s-frontend" (include "eks-setup-app.fullname" .)) .Values.frontend.serviceAccount.name }}
  labels:
    {{- include "eks-setup-app.labels" . | nindent 4 }}
    {{- include "eks-setup-app.componentLabels" (dict "component" "frontend" "Release" .Release "Chart" .Chart "Values" .Values) | nindent 4 }}
  {{- with .Values.frontend.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}


