{{- if .Values.frontend.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "eks-setup-app.fullname" . }}-frontend
  labels:
    {{- include "eks-setup-app.labels" . | nindent 4 }}
    {{- include "eks-setup-app.componentLabels" (dict "component" "frontend" "Release" .Release "Chart" .Chart "Values" .Values) | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      {{- include "eks-setup-app.componentLabels" (dict "component" "frontend" "Release" .Release "Chart" .Chart "Values" .Values) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "eks-setup-app.componentLabels" (dict "component" "frontend" "Release" .Release "Chart" .Chart "Values" .Values) | nindent 8 }}
    spec:
      automountServiceAccountToken: false
      {{- with .Values.global.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.frontend.serviceAccount.create }}
      serviceAccountName: {{ default (printf "%s-frontend" (include "eks-setup-app.fullname" .)) .Values.frontend.serviceAccount.name }}
      {{- end }}
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.global.containerSecurityContext | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.frontend.service.port }}
          env:
            {{- range $k, $v := .Values.frontend.env }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: {{ .Values.frontend.probes.liveness.path }}
              port: http
            initialDelaySeconds: {{ .Values.frontend.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.frontend.probes.liveness.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.frontend.probes.readiness.path }}
              port: http
            initialDelaySeconds: {{ .Values.frontend.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.frontend.probes.readiness.periodSeconds }}
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
{{- end }}


